
services:
  webscraper:
    image: webscrape
    build:
      context: ./OSGC_webscraper
      dockerfile: Dockerfile
    volumes:
      - root_OSGC:/data
  API:
    image: osgc_api
    mem_limit: 4g
    build:
      context: ./OSGC_API
      dockerfile: Dockerfile
    volumes:
      - root_OSGC:/data
    ports:
      - "8080:8080"
volumes:
  root_OSGC:
    driver: local
